window.data.csharp = {
  "ref and out in c#": {
    "answer": `
    <ul>
        <li>
            Both <code>ref</code> and <code>out</code> pass parameters by reference.
        </li>

        <li>
            With <code>ref</code>, the variable <strong>must be initialized</strong> before calling the method
            because the method can read and modify its existing value.
        </li>

        <li>
            With <code>out</code>, the variable <strong>does not need to be initialized</strong>.
            However, the called method <strong>must assign a value</strong> before returning.
        </li>

        <li>
            <code>ref</code> is mainly used to <strong>modify existing data</strong>,
            while <code>out</code> is primarily used to
            <strong>return additional values</strong>, such as in
            <code>int.TryParse()</code>.
        </li>
    </ul>
    `
  },
  "Benefit of using statement in C#": {
    "answer": `
    <p>
        The <code>using</code> statement ensures that an object is
        <strong>automatically disposed</strong> after it is used, even if an exception occurs.
        It helps prevent resource leaks by releasing unmanaged resources such as files,
        database connections, streams, and network objects.
    </p>

    <ul>
        <li>Automatically calls the <code>Dispose()</code> method.</li>
        <li>Prevents memory and resource leaks.</li>
        <li>Makes code cleaner and easier to maintain.</li>
        <li>Works with classes that implement the <code>IDisposable</code> interface.</li>
    </ul>

    <div class="tip">
        <strong>Interview Tip:</strong><br>
        <code>using</code> is syntactic sugar for a <code>try-finally</code> block where
        <code>Dispose()</code> is called in the <code>finally</code> block.
    </div>
    `
},
"finally block and Finalize() method": {
    "answer": `
    <table class="table table-bordered">
        <tr>
            <th>finally Block</th>
            <th>Finalize() Method</th>
        </tr>

        <tr>
            <td>Used for resource cleanup.</td>
            <td>Used to clean up unmanaged resources before an object is garbage collected.</td>
        </tr>

        <tr>
            <td>Executes immediately after the <code>try</code> block, whether or not an exception occurs.</td>
            <td>Executed by the Garbage Collector (GC) before the object is destroyed.</td>
        </tr>

        <tr>
            <td>Execution is deterministic (runs at a known time).</td>
            <td>Execution is non-deterministic (GC decides when to run it).</td>
        </tr>

        <tr>
            <td>Can be used with <code>try-catch</code> or <code>try</code>.</td>
            <td>Cannot be called directly by user code.</td>
        </tr>

        <tr>
            <td>Mainly used to close files, database connections, streams, etc.</td>
            <td>Mainly used to release unmanaged resources if <code>IDisposable</code> is not implemented.</td>
        </tr>
    </table>
    `
},
"Partial Class": {
    "answer": `
    <p>
        A <code>Partial Class</code> allows the definition of a single class to be
        split across multiple source files. At compile time, the C# compiler combines
        all the partial class definitions into a single class.
    </p>

    <ul>
        <li>Splits a large class into multiple files for better maintainability.</li>
        <li>All parts must use the <code>partial</code> keyword.</li>
        <li>All partial class files must have the same class name and namespace.</li>
        <li>Commonly used in Windows Forms, Entity Framework, and code generated by Visual Studio.</li>
    </ul>

    <div class="tip">
        <strong>🎯 Interview Tip:</strong><br>
        A <code>Partial Class</code> helps separate developer-written code from
        auto-generated code, preventing custom changes from being overwritten when
        the generated code is regenerated.
    </div>
    `
},
"Reference Types and Value Types": {
    "answer": `
    <p>
        <strong>Value Types</strong> store the actual data and usually reside on the stack.
        Each variable has its own copy, so changes to one variable don't affect another.
        Examples include <code>int</code>, <code>bool</code>, <code>double</code>, and <code>struct</code>.
    </p>

    <p>
        <strong>Reference Types</strong> store a reference to an object that resides on the heap.
        Multiple variables can reference the same object, so changes made through one reference
        are reflected in the others. Examples include <code>class</code>, <code>string</code>,
        <code>array</code>, and <code>interface</code>.
    </p>
    `
},
"Sealed Classes": {
    "answer": `
    <p>
        A <code>sealed</code> class is a class that <strong>cannot be inherited</strong>.
        Once a class is marked as <code>sealed</code>, no other class can derive from it.
        It is used to prevent further inheritance and protect the class implementation.
    </p>

    <p>
        Sealed classes are commonly used when a class is complete, for security reasons,
        or to prevent accidental modification through inheritance.
    </p>
    `
},

"What is throw and throw ex in .NET?": {
    "answer": `
    <p>
        Both <code>throw</code> and <code>throw ex</code> are used to rethrow exceptions,
        but they differ in how they preserve exception information.
    </p>

    <p>
        <code>throw</code> preserves the <strong>original stack trace</strong>, making it easier
        to identify where the exception actually occurred. In contrast,
        <code>throw ex</code> resets the stack trace, causing the exception to appear as if it
        originated from the current catch block, which makes debugging more difficult.
    </p>

    <p>
        Therefore, <strong>always use <code>throw</code> to rethrow an existing exception</strong>
        unless you intentionally want to create a new exception.
    </p>
    `
},
"What are Nullable Reference Types (C# 8+)?": {
    "answer": `
    <p>
        <strong>Nullable Reference Types</strong>, introduced in <strong>C# 8.0</strong>,
        help developers avoid <strong>NullReferenceException</strong> by making the compiler
        distinguish between nullable and non-nullable reference types.
    </p>

    <p>
        By default, a reference type is considered <strong>non-nullable</strong>. To allow
        null values, the type must be declared using the <code>?</code> operator, such as
        <code>string?</code>. The compiler generates warnings if a nullable value is not
        handled properly.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li>Preventing <code>NullReferenceException</code>.</li>
        <li>Writing safer and more reliable code.</li>
        <li>Improving code quality through compile-time null checks.</li>
        <li>Making APIs more self-documenting by indicating whether null values are allowed.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        Nullable Reference Types help prevent NullReferenceException by enabling compile-time null checking for reference types.
    </div>
    `
},
"What is Reflection in C#?": {
    "answer": `
    <p>
        <strong>Reflection</strong> is a feature in C# that allows a program to
        inspect and interact with its own metadata at runtime. Using Reflection,
        you can examine assemblies, classes, methods, properties, fields, and
        dynamically create objects or invoke methods.<br/>
        Reflection is a feature in .NET that allows you to inspect and manipulate metadata about assemblies, types, methods, properties, fields, and attributes at runtime.
    </p>

    <p>
        Reflection is provided by the <code>System.Reflection</code> namespace
        and is commonly used in frameworks, dependency injection, unit testing,
        serialization, and plugin-based applications.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li>Inspecting types and assemblies at runtime.</li>
        <li>Dynamically creating objects and invoking methods.</li>
        <li>Building Dependency Injection (DI) frameworks.</li>
        <li>Serialization and deserialization.</li>
        <li>Loading plugins or external assemblies dynamically.</li>
        <li>Creating testing and ORM frameworks.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        Reflection is the ability of a program to inspect and manipulate its own metadata and types at runtime.
    </div>
    `
},
"constant and readonly in C#?": {
    "answer": `
    <p>
        Both <code>const</code> and <code>readonly</code> are used to define values
        that should not be modified after initialization, but they differ in when
        and how they are assigned.
    </p>

    <p>
        A <code>const</code> variable is a compile-time constant. Its value must
        be assigned at the time of declaration and cannot be changed.
        A <code>readonly</code> field is a runtime constant that can be assigned
        either at declaration or inside the constructor.
    </p>

    <p><strong>Key Differences:</strong></p>

    <ul>
        <li><strong>const</strong> → Value is fixed at compile time.</li>
        <li><strong>readonly</strong> → Value is assigned at runtime.</li>
        <li><strong>const</strong> must be initialized during declaration.</li>
        <li><strong>readonly</strong> can be initialized at declaration or in the constructor.</li>
        <li><strong>const</strong> is implicitly static.</li>
        <li><strong>readonly</strong> can be either instance-level or static.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        Use <code>const</code> for values that never change and are known at compile time, and <code>readonly</code> for values that are initialized at runtime and remain unchanged thereafter.
    </div>
    `
},
"Deep Copy and Shallow Copy in C#?": {
    "answer": `
    <p>
        Both <strong>Shallow Copy</strong> and <strong>Deep Copy</strong> are used
        to create copies of objects, but they differ in how reference type members
        are copied.
    </p>

    <p>
        A <strong>Shallow Copy</strong> copies the object's value type fields but
        copies only the references of reference type fields. As a result, both
        objects share the same referenced objects.
    </p>

    <p>
        A <strong>Deep Copy</strong> creates a completely independent copy of the
        object, including all nested reference type objects. Changes made to one
        object do not affect the other.
    </p>

    <p><strong>Key Differences:</strong></p>

    <ul>
        <li><strong>Shallow Copy</strong> → Copies object references.</li>
        <li><strong>Deep Copy</strong> → Copies the entire object graph.</li>
        <li><strong>Shallow Copy</strong> → Changes to nested objects affect both copies.</li>
        <li><strong>Deep Copy</strong> → Changes to nested objects do not affect the original object.</li>
        <li><strong>Shallow Copy</strong> → Faster and uses less memory.</li>
        <li><strong>Deep Copy</strong> → Slower but creates completely independent objects.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        A shallow copy copies object references, whereas a deep copy creates a completely independent copy of the object and all its referenced objects.
    </div>
    `
},
"How is Encapsulation done in C#?": {
    "answer": `
    <p>
        <strong>Encapsulation</strong> is one of the four fundamental principles
        of Object-Oriented Programming (OOP). It is the process of binding data
        (fields) and methods into a single unit (class) while restricting direct
        access to the data.
    </p>

    <p>
        In C#, encapsulation is achieved by declaring fields as
        <code>private</code> and providing controlled access through
        <code>public</code> properties or methods.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li>Protecting sensitive data from unauthorized access.</li>
        <li>Validating data before updating object state.</li>
        <li>Hiding implementation details.</li>
        <li>Improving code security and maintainability.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        Encapsulation in C# is achieved by making data members private and exposing them through public properties or methods to provide controlled access.
    </div>
    `
},
  "Abstract Class": {
    "answer": `
<h2>Abstract Class</h2>

<h3>Definition</h3>
<p>
An abstract class is a class that cannot be instantiated directly.
It serves as a base class for other classes and can contain both
abstract and concrete methods.
</p>

<h3>Key Points</h3>
<ul>
<li>Cannot create object directly</li>
<li>Can contain abstract and non-abstract methods</li>
<li>Can have constructors</li>
<li>Supports inheritance</li>
<li>Used for code reuse</li>
</ul>
`
  },
  "How is Abstraction done in C#?": {
    "answer": `
    <p>
        <strong>Abstraction</strong> is one of the four fundamental principles
        of Object-Oriented Programming (OOP). It is the process of hiding
        implementation details and exposing only the essential functionality
        to the user.
    </p>

    <p>
        In C#, abstraction is achieved using <strong>abstract classes</strong>
        and <strong>interfaces</strong>. These define what an object should do,
        while the derived class provides the implementation.
    </p>
    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        Abstraction in C# is achieved using abstract classes and interfaces, which hide implementation details and expose only essential functionality.
    </div>
    `
},
  "Abstract Class and an Interface?": {
    "answer": `
    <table class="table table-bordered">
        <tr>
            <th>Abstract Class</th>
            <th>Interface</th>
        </tr>

        <tr>
            <td>Can contain both abstract and concrete (implemented) methods.</td>
            <td>Contains method declarations. (Modern C# also supports default implementations.)</td>
        </tr>

        <tr>
            <td>Can have constructors.</td>
            <td>Cannot have constructors.</td>
        </tr>

        <tr>
            <td>Can have instance fields.</td>
            <td>Cannot have instance fields.</td>
        </tr>

        <tr>
            <td>A class can inherit only one abstract class.</td>
            <td>A class can implement multiple interfaces.</td>
        </tr>

        <tr>
            <td>Used to share common code and state among related classes.</td>
            <td>Used to define a contract that unrelated classes can implement.</td>
        </tr>
    </table>

    <div class="tip">
        <strong>🎯 Interview Tip:</strong><br>
        Use an <code>Abstract Class</code> when classes share common implementation and state.<br>
        Use an <code>Interface</code> when different classes need to follow the same contract.
    </div>
    `
  },
  "Why Interface Does Not Have Constructor": {
    "answer": `

<h3>Answer</h3>

<ul>
<li>Interface cannot contain fields</li>
<li>Interface does not maintain state</li>
<li>No object can be created from interface</li>
<li>Nothing exists to initialize</li>
</ul>

<h3>Interview Answer</h3>

<p>
Since interfaces only define contracts and do not
store data, constructors are not required.
</p>
`
  },
  "Why Abstract Class Can Have Constructor": {
    "answer": `
<h2>Why Abstract Class Can Have Constructor</h2>

<h3>Answer</h3>

<ul>
<li>Abstract class can contain fields</li>
<li>Can maintain shared state</li>
<li>Used to initialize common data</li>
<li>Called automatically by derived class constructor</li>
</ul>

<h3>Example</h3>

<pre>
public abstract class Employee
{
    protected string Name;

    protected Employee(string name)
    {
        Name = name;
    }
}
</pre>
`
  },
  "Constructor": {
    "answer": `
<h2>Constructor</h2>

<h3>Definition</h3>

<p>
A constructor is a special method that is executed
automatically when an object is created.
</p>

<h3>Features</h3>

<ul>
<li>Same name as class</li>
<li>No return type</li>
<li>Used for initialization</li>
<li>Called automatically</li>
</ul>

<h3>Example</h3>

<pre>
public class Employee
{
    public Employee() n    { n        Console.WriteLine("Created"); n    } n} n</pre> n
<h3>Real Project Example</h3> n
<pre"> npublic EmployeeService(IRepository repo) n{ n    _repo = repo; n} n</pre"> n
<p"> nThis is Constructor Injection used in .NET Core. n</p"> n`
  },
  "Default Constructor": {
    "answer": `
<h2>Default Constructor</h2>

<h3>Definition</h3>

<p>
A constructor without parameters.
</p>

<h3>Example</h3>

<pre>
public class Employee
{
    public Employee()
    {
    }
}
</pre>

<h3>Usage</h3>

<p>
Used when object should be initialized with default values.
</p>
`
  },
  "Parameterized Constructor": {
    "answer": `
<h2>Parameterized Constructor</h2>

<h3>Definition</h3>

<p>
A constructor that accepts parameters.
</p>

<h3>Example</h3>

<pre>
public class Employee
{
    public string Name;

    public Employee(string name)
    {
        Name = name;
    }
}
</pre>

<h3>Benefits</h3>

<ul>
<li>Initialize custom values</li>
<li>Improve object consistency</li>
<li>Used in Dependency Injection</li>
</ul>
`
  },
  "Polymorphism": {
    "answer": `
<h2>Polymorphism</h2>

<h3>Definition</h3>

<p>
One Interface, Many Forms.
The same method can behave differently depending on implementation.
</p>

<h3>Types of Polymorphism</h3>

<h4>1. Compile Time Polymorphism</h4>

<p>Method Overloading</p>

<pre>
public int Add(int a,int b) n{ n    return a+b; n} n
public int Add(int a,int b,int c) n{ n    return a+b+c; n} n</pre> n
<h4>2. Runtime Polymorphism</h4> n
<p>Method Overriding</p> n
<pre"> npublic virtual void Print() n{ n} n
public override void Print() n{ n} n</pre"> n
<h3>Interview Answer</h3> n
<p"> nRuntime Polymorphism is heavily used in enterprise applications
through interfaces, abstract classes and dependency injection. n</p"> n`
  },
  "What is a Destructor in C# and when is it used?": {
    "answer": `
    <p>
        A <strong>Destructor</strong> is a special method in C# that is
        automatically called by the <strong>Garbage Collector (GC)</strong>
        before an object is removed from memory. It is used to perform
        cleanup of unmanaged resources.
    </p>

    <p>
        A destructor has the same name as the class, prefixed with a
        <code>~</code> (tilde), and it has no return type or parameters.
        Developers cannot call a destructor explicitly.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li>Releasing unmanaged resources.</li>
        <li>Closing file handles or database connections (when not handled by IDisposable).</li>
        <li>Cleaning up native resources before an object is destroyed.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        A destructor is automatically executed by the Garbage Collector to clean up unmanaged resources before an object is destroyed.
    </div>
    `
},
"What is the let keyword in C#?": {
    "answer": `
    <p>
        The <strong>let</strong> keyword is used in <strong>LINQ query syntax</strong>
        to create a temporary variable that stores the result of an expression.
        This variable can be reused later in the same query, improving readability
        and avoiding repeated calculations.
    </p>

    <p>
        The <code>let</code> keyword is available only in LINQ query expressions
        and is not used for declaring variables in regular C# code.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li>Storing intermediate calculation results.</li>
        <li>Avoiding repeated expressions in LINQ queries.</li>
        <li>Improving the readability of complex LINQ queries.</li>
        <li>Reusing calculated values in filtering and projection.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        The <code>let</code> keyword in LINQ creates a temporary variable to store an expression result, making queries more readable and efficient.
    </div>
    `
},
"What is the difference between Task and Thread in C#?": {
    "answer": `
    <p>
        A <strong>Thread</strong> is the basic unit of execution managed by the
        operating system, whereas a <strong>Task</strong> is a higher-level
        abstraction that represents an asynchronous operation managed by the
        .NET Task Parallel Library (TPL).
    </p>

    <p>
        Tasks are lightweight, easier to manage, and make efficient use of the
        .NET Thread Pool. In modern .NET applications, <strong>Task</strong> is
        preferred over manually creating threads.
    </p>

    <p><strong>Key Differences:</strong></p>

    <ul>
        <li><strong>Thread</strong> → Managed by the Operating System.</li>
        <li><strong>Task</strong> → Managed by the .NET Task Parallel Library (TPL).</li>
        <li><strong>Thread</strong> → Creates a dedicated thread.</li>
        <li><strong>Task</strong> → Reuses Thread Pool threads whenever possible.</li>
        <li><strong>Thread</strong> → More memory and resource intensive.</li>
        <li><strong>Task</strong> → Lightweight and better performing.</li>
        <li><strong>Task</strong> → Supports <code>async/await</code>, continuation, cancellation and exception handling.</li>
    </ul>

    <p><strong>Implementation Example:</strong></p>

    <p><strong>Using Thread</strong></p>

    <pre><code class="language-csharp">
Thread thread = new Thread(() =>
{
    Console.WriteLine("Running on Thread");
});

thread.Start();
    </code></pre>

    <p><strong>Using Task</strong></p>

    <pre><code class="language-csharp">
Task.Run(() =>
{
    Console.WriteLine("Running on Task");
});
    </code></pre>

    <p><strong>Real-Time Example:</strong></p>

    <p>
        In an ASP.NET Core application, when calling an external Payment API,
        developers typically use <code>Task</code> with
        <code>async/await</code> because it efficiently uses thread pool
        threads. Creating dedicated threads for every API request would consume
        unnecessary resources and reduce scalability.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li><strong>Task</strong> - Web APIs, database calls, file I/O, microservices.</li>
        <li><strong>Thread</strong> - Long-running background processing requiring a dedicated thread (rare in modern .NET applications).</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        A Thread is an operating system-level execution unit, while a Task is a lightweight abstraction managed by the .NET Task Parallel Library. In modern .NET applications, Task is preferred because it efficiently uses the Thread Pool and supports async programming.
    </div>
    `
},
"Caching and What are its types in C#?": {
    "answer": `
    <p>
        <strong>Caching</strong> is the process of storing frequently accessed
        data in temporary storage so that future requests can be served faster
        without repeatedly fetching data from the database or external services.
    </p>

    <p>
        Caching improves application performance, reduces database load,
        minimizes network calls, and enhances the overall user experience.
    </p>

    <p><strong>Types of Caching:</strong></p>

    <ul>
        <li><strong>In-Memory Cache (IMemoryCache)</strong> - Stores data in the application's memory. Best for single-server applications.</li>
        <li><strong>Distributed Cache (IDistributedCache)</strong> - Stores data in distributed storage such as Redis or SQL Server. Best for multi-server applications.</li>
        <li><strong>Response Caching</strong> - Caches HTTP responses to improve Web API performance.</li>
        <li><strong>Output Caching (.NET 7+)</strong> - Caches the output of API endpoints or pages for improved scalability.</li>
    </ul>

    <p><strong>Implementation Example (IMemoryCache):</strong></p>

    <pre><code class="language-csharp">
// Register Memory Cache
builder.Services.AddMemoryCache();
    </code></pre>

    <pre><code class="language-csharp">
public class ProductService
{
    private readonly IMemoryCache _cache;

    public ProductService(IMemoryCache cache)
    {
        _cache = cache;
    }

    public List&lt;Product&gt; GetProducts()
    {
        return _cache.GetOrCreate("Products", entry =>
        {
            entry.AbsoluteExpirationRelativeToNow =
                TimeSpan.FromMinutes(10);

            return GetProductsFromDatabase();
        });
    }
}
    </code></pre>

    <p><strong>Real-Time Example:</strong></p>

    <p>
        In an e-commerce application, the product catalog is frequently requested.
        Instead of querying the database for every request, the product list is
        stored in the cache. Subsequent requests retrieve the data directly from
        the cache, significantly improving response time and reducing database load.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li>Product catalogs.</li>
        <li>Lookup and master data.</li>
        <li>User profile information.</li>
        <li>Configuration settings.</li>
        <li>Frequently accessed API responses.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        Caching improves application performance by storing frequently accessed data in temporary storage. ASP.NET Core supports IMemoryCache, IDistributedCache, Response Caching, and Output Caching.
    </div>
    `
},
"Cross-Site Scripting (XSS) attacks": {
    "answer": `
    <p>
        <strong>Cross-Site Scripting (XSS)</strong> is a security vulnerability
        in which an attacker injects malicious JavaScript into a web page.
        When other users open the page, the malicious script executes in their
        browser, potentially stealing cookies, session tokens, or sensitive data.
    </p>

    <p>
        ASP.NET Core provides built-in features to protect applications from XSS,
        such as automatic HTML encoding in Razor views. Additional protection
        includes input validation, Content Security Policy (CSP), and secure cookies.
    </p>

    <p><strong>Protection Strategies:</strong></p>

    <ul>
        <li>Use Razor's automatic HTML encoding.</li>
        <li>Validate and sanitize all user input.</li>
        <li>Avoid rendering raw HTML unless absolutely necessary.</li>
        <li>Implement Content Security Policy (CSP).</li>
        <li>Use HttpOnly and Secure cookies.</li>
        <li>Encode output before displaying user input.</li>
    </ul>

    <p><strong>Implementation Example:</strong></p>

    <p><strong>Safe (Automatically Encoded)</strong></p>

    <pre><code class="language-csharp">
@Model.UserName
    </code></pre>

    <p><strong>Unsafe (Avoid)</strong></p>

    <pre><code class="language-csharp">
@Html.Raw(Model.UserName)
    </code></pre>

    <p><strong>Real-Time Example:</strong></p>

    <p>
        Suppose a user enters
        <code>&lt;script&gt;alert('Hacked')&lt;/script&gt;</code>
        as their name. Razor automatically encodes the value and displays it as
        plain text instead of executing it as JavaScript, preventing an XSS attack.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li>Login and Registration forms.</li>
        <li>Comment sections.</li>
        <li>Contact forms.</li>
        <li>User profile pages.</li>
        <li>Any page displaying user-generated content.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        Protect ASP.NET Core applications from XSS by using automatic HTML encoding, validating user input, avoiding raw HTML rendering, implementing CSP, and using secure cookies.
    </div>
    `
},
"Difference between Delegate and Event in C#": {
    "answer": `
    <p>
        Both <strong>Delegate</strong> and <strong>Event</strong> are used to
        implement callbacks and event-driven programming in C#. An
        <strong>Event</strong> is built on top of a <strong>Delegate</strong>,
        but it provides additional security by restricting who can invoke it.
    </p>

    <p><strong>Key Differences:</strong></p>

    <table border="1" cellpadding="5" cellspacing="0">
        <tr>
            <th>Delegate</th>
            <th>Event</th>
        </tr>

        <tr>
            <td>Represents a reference to one or more methods.</td>
            <td>Represents a notification mechanism built on delegates.</td>
        </tr>

        <tr>
            <td>Can be invoked from anywhere if accessible.</td>
            <td>Can only be raised by the class that declares it.</td>
        </tr>

        <tr>
            <td>Used for callbacks and passing methods as parameters.</td>
            <td>Used for publisher-subscriber communication.</td>
        </tr>

        <tr>
            <td>Supports direct method invocation.</td>
            <td>Subscribers can only subscribe or unsubscribe using += or -=.</td>
        </tr>
    </table>

    <p><strong>Implementation Example:</strong></p>

    <p><strong>Delegate</strong></p>

    <pre><code class="language-csharp">
public delegate void Notify();

Notify notify = ShowMessage;
notify();

void ShowMessage()
{
    Console.WriteLine("Hello");
}
    </code></pre>

    <p><strong>Event</strong></p>

    <pre><code class="language-csharp">
public class OrderService
{
    public event Action OrderPlaced;

    public void PlaceOrder()
    {
        Console.WriteLine("Order Created");

        OrderPlaced?.Invoke();
    }
}
    </code></pre>

    <p><strong>Real-Time Example:</strong></p>

    <p>
        In an e-commerce application, when an order is placed, the
        <strong>OrderService</strong> raises an event. Multiple subscribers
        such as <strong>Email Service</strong>, <strong>SMS Service</strong>,
        and <strong>Inventory Service</strong> receive the notification and
        perform their respective actions.
    </p>

    <p><strong>Common Use Cases:</strong></p>

    <ul>
        <li><strong>Delegate</strong> - Callbacks, LINQ, asynchronous programming.</li>
        <li><strong>Event</strong> - Button click events, Order notifications, Publisher-Subscriber pattern.</li>
    </ul>

    <div class="interview-answer">
        <strong>Interview One-Liner:</strong>
        A Delegate is a type-safe function pointer used to invoke methods, whereas an Event is a delegate-based notification mechanism that allows only the publisher to raise the event.
    </div>
    `
},
"Difference between Hashtable and Generic Collections": {
    "answer": `
    <p>
        <strong>Hashtable</strong> is a non-generic collection introduced in .NET 1.0
        that stores key-value pairs as <strong>object</strong> types.
        <strong>Generic Collections</strong>, introduced in .NET 2.0, provide
        type-safe collections such as Dictionary&lt;TKey, TValue&gt;, List&lt;T&gt;,
        and HashSet&lt;T&gt;.
    </p>

    <p><strong>Comparison</strong></p>

    <pre><code class="language-text">
Hashtable
      │
      ├── Non-Generic
      ├── Stores object/object
      ├── Boxing/Unboxing
      └── Runtime Type Checking

                VS

Generic Collections
      │
      ├── Type Safe
      ├── Better Performance
      ├── Compile-time Type Checking
      └── No Boxing/Unboxing
    </code></pre>

    <p><strong>Hashtable Example</strong></p>

    <pre><code class="language-csharp">
Hashtable ht = new Hashtable();

ht.Add(1, "John");
ht.Add(2, "David");

string name = (string)ht[1];
    </code></pre>

    <p><strong>Dictionary Example</strong></p>

    <pre><code class="language-csharp">
Dictionary&lt;int, string&gt; users =
    new Dictionary&lt;int, string&gt;();

users.Add(1, "John");
users.Add(2, "David");

string name = users[1];
    </code></pre>

    <p><strong>Key Differences</strong></p>

    <ul>
        <li>Hashtable is non-generic; Dictionary is generic.</li>
        <li>Hashtable stores keys and values as object; Dictionary uses specific data types.</li>
        <li>Hashtable requires casting; Dictionary does not.</li>
        <li>Dictionary provides compile-time type safety.</li>
        <li>Dictionary avoids boxing and unboxing for value types.</li>
        <li>Dictionary generally offers better performance.</li>
    </ul>

    <p><strong>Interview One-Liner:</strong></p>

    <div class="interview-answer">
        Hashtable is a legacy non-generic collection that stores object types,
        whereas Generic Collections like Dictionary&lt;TKey, TValue&gt; are
        type-safe, faster, and preferred in modern .NET applications.
    </div>
    `
},
"What is the null-coalescing operator (??) and null-conditional operator (?.)?": {
    "answer": `
    <p>
        The <strong>null-coalescing operator (??)</strong> returns the left-hand
        operand if it is not <strong>null</strong>; otherwise, it returns the
        right-hand operand. It is commonly used to provide default values.
    </p>

    <p>
        The <strong>null-conditional operator (?.)</strong> safely accesses
        members of an object. If the object is <strong>null</strong>, the
        operation stops and returns <strong>null</strong> instead of throwing
        a <strong>NullReferenceException</strong>.
    </p>

    <p><strong>Example</strong></p>

    <pre><code class="language-csharp">
string name = null;

string display = name ?? "Guest";
// Output: Guest

int? len = name?.Length;
// Output: null (No Exception)

Console.WriteLine(name?.ToUpper() ?? "No name");
// Output: No name
    </code></pre>

    <p><strong>Use Cases</strong></p>

    <ul>
        <li><strong>??</strong> - Assign a default value when an object is null.</li>
        <li><strong>?.</strong> - Safely access properties, methods, or fields without null checks.</li>
        <li>Both operators can be combined to write concise, null-safe code.</li>
    </ul>

    <p><strong>Interview One-Liner:</strong></p>

    <div class="interview-answer">
        The <strong>??</strong> operator provides a default value when an object
        is null, while the <strong>?.</strong> operator safely accesses object
        members without throwing a NullReferenceException. Together, they simplify
        null handling and improve code readability.
    </div>
    `
},
"What are init-only setters and what problem do they solve?": {
    "answer": `
    <p>
        <strong>Init-only setters</strong> were introduced in <strong>C# 9.0</strong>.
        They allow a property to be assigned only during <strong>object initialization</strong>
        or inside a constructor. Once the object is created, the property becomes
        <strong>read-only</strong> and cannot be modified.
    </p>

    <p>
        Init-only setters solve the problem of creating
        <strong>immutable objects</strong> while still allowing the convenient
        object initializer syntax. They are commonly used for
        <strong>DTOs, configuration objects, and records</strong>.
    </p>

    <p><strong>How init Works</strong></p>

    <pre><code class="language-text">
Object Creation
      │
      ▼
Initialize Properties
(using init)
      │
      ▼
Object Created
      │
      ▼
Properties Become Read-Only
    </code></pre>

    <p><strong>Example</strong></p>

    <pre><code class="language-csharp">
public class Order
{
    public int Id { get; init; }

    public string Product { get; init; }
}

var order = new Order
{
    Id = 1,
    Product = "Book"
};

// Compile-time Error
order.Id = 2;
    </code></pre>

    <p><strong>Benefits</strong></p>

    <ul>
        <li>Supports immutable object design.</li>
        <li>Allows object initializer syntax.</li>
        <li>Prevents accidental property modification.</li>
        <li>Improves thread safety.</li>
        <li>Ideal for DTOs, records, and configuration classes.</li>
    </ul>

    <p><strong>init vs set</strong></p>

    <ul>
        <li><strong>set</strong> - Property can be modified anytime.</li>
        <li><strong>init</strong> - Property can only be assigned during object creation.</li>
    </ul>

    <p><strong>Interview One-Liner:</strong></p>

    <div class="interview-answer">
        Init-only setters allow properties to be assigned only during object
        initialization, providing immutable objects while retaining the simplicity
        of object initializer syntax. They are commonly used for DTOs, records,
        and configuration objects.
    </div>
    `
},
"Difference between ASP.NET Framework and ASP.NET Core": {
    "answer": `
    <p>
        <strong>ASP.NET Framework</strong> is the traditional Microsoft web
        framework that runs only on Windows and is tightly coupled with the
        .NET Framework. <strong>ASP.NET Core</strong> is a modern, lightweight,
        open-source, cross-platform framework for building cloud-native and
        high-performance web applications.
    </p>

    <p><strong>Architecture Overview</strong></p>

    <pre><code class="language-text">
ASP.NET Framework
       │
       ▼
.NET Framework
       │
       ▼
Windows Only
       │
       ▼
IIS


ASP.NET Core
       │
       ▼
.NET (.NET Core / .NET 5+)
       │
       ▼
Windows | Linux | macOS
       │
       ▼
Kestrel + IIS / Nginx / Apache
    </code></pre>

    <p><strong>Key Differences</strong></p>

    <ul>
        <li><strong>Platform</strong> - ASP.NET Framework runs only on Windows, whereas ASP.NET Core is cross-platform.</li>
        <li><strong>Performance</strong> - ASP.NET Core is significantly faster and optimized for modern applications.</li>
        <li><strong>Hosting</strong> - ASP.NET Framework uses IIS, whereas ASP.NET Core uses Kestrel and can also run behind IIS, Nginx, or Apache.</li>
        <li><strong>Dependency Injection</strong> - Built-in support in ASP.NET Core; external libraries are typically required in ASP.NET Framework.</li>
        <li><strong>Configuration</strong> - ASP.NET Framework uses Web.config, whereas ASP.NET Core uses appsettings.json and Program.cs.</li>
        <li><strong>Deployment</strong> - ASP.NET Core supports self-contained deployment and side-by-side runtime versions.</li>
        <li><strong>Middleware</strong> - ASP.NET Core uses a middleware pipeline; ASP.NET Framework uses the HTTP Module and HTTP Handler pipeline.</li>
        <li><strong>Cloud Support</strong> - ASP.NET Core is designed for cloud and microservices architectures.</li>
    </ul>

    <p><strong>Configuration Example</strong></p>

    <pre><code class="language-text">
ASP.NET Framework
-----------------
Web.config
Global.asax


ASP.NET Core
------------
Program.cs
appsettings.json
Middleware
    </code></pre>

    <p><strong>Advantages of ASP.NET Core</strong></p>

    <ul>
        <li>Cross-platform support.</li>
        <li>High performance.</li>
        <li>Built-in Dependency Injection.</li>
        <li>Built-in Middleware pipeline.</li>
        <li>Cloud-ready and container-friendly.</li>
        <li>Excellent support for Microservices and REST APIs.</li>
    </ul>

    <p><strong>Real-Time Example</strong></p>

    <p>
        In my current project, we migrated applications from
        <strong>ASP.NET Framework 3.5/4.x</strong> to a modern platform by
        upgrading frameworks and related libraries, improving browser
        compatibility, application performance, and maintainability.
        For new development, we use ASP.NET Core because of its better
        performance, built-in Dependency Injection, middleware pipeline,
        and cloud support.
    </p>

    <p><strong>Interview One-Liner:</strong></p>

    <div class="interview-answer">
        ASP.NET Framework is a Windows-only web framework built on the .NET Framework,
        whereas ASP.NET Core is a modern, cross-platform, high-performance framework
        with built-in Dependency Injection, middleware, and cloud-native support.
    </div>
    `
},
};
